import { PrismaService } from '../prisma.service';
import { Shift, Prisma } from '@unitedlinkgroup/database';
import { NotificationsService } from '../notifications/notifications.service';
import { PushService } from '../push/push.service';
import { AuditService } from '../audit/audit.service';
export declare class SchedulingService {
    private prisma;
    private notifications;
    private push;
    private audit;
    constructor(prisma: PrismaService, notifications: NotificationsService, push: PushService, audit: AuditService);
    private validateBusinessAccess;
    private resolveActorUserId;
    private assertNoShiftOverlap;
    private getEmployeeForActor;
    private getAdminUsersForBusiness;
    private notifyOpenShiftCandidates;
    recordCallout(shiftId: string, body: any, user: any, meta?: {
        ipAddress?: string;
        userAgent?: string;
    }): Promise<{
        shiftId: string;
        calloutId: any;
        status: string;
    }>;
    listPendingCallouts(user: any, businessIdHeader?: string): Promise<any>;
    approveCallout(calloutId: string, user: any): Promise<{
        callout: any;
        notified: number;
    }>;
    rejectCallout(calloutId: string, body: any, user: any): Promise<any>;
    getMyCallouts(userId: string): Promise<any>;
    reassignShift(shiftId: string, body: any, user: any, meta?: {
        ipAddress?: string;
        userAgent?: string;
    }): Promise<{
        shift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        coverageId: any;
    }>;
    broadcastOpenShift(shiftId: string, body: any, user: any, meta?: {
        ipAddress?: string;
        userAgent?: string;
    }): Promise<{
        shiftId: string;
        notified: number;
    }>;
    getShiftHistory(shiftId: string, user: any): Promise<{
        shift: {
            [x: string]: ({
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            })[] | ({
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            })[] | ({
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            } | {
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            })[] | {
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            }[] | {
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            }[] | {
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            }[];
            [x: number]: never;
            [x: symbol]: never;
        } & {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        logs: {
            id: string;
            action: string;
            resource: string;
            resourceId: string | null;
            at: Date;
            by: string;
            details: any;
        }[];
    }>;
    createShift(data: Prisma.ShiftCreateInput, user: any): Promise<Shift>;
    getTaxContextForBusiness(userId: string, locationId?: string): Promise<import("../common/tax.util").TaxContext>;
    getShifts(businessId: string, start: Date, end: Date, user: any, employeeId?: string): Promise<Shift[]>;
    applyForShift(shiftId: string, userId: string): Promise<any>;
    declineShiftApplication(applicationId: string, user: any): Promise<{
        success: boolean;
    }>;
    approveShiftApplication(applicationId: string, user: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }>;
    getMyShifts(userId: string, start: Date, end: Date): Promise<{
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            hourlyRate: number;
        };
        shifts: ({
            employee: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
            location: {
                id: string;
                businessId: string;
                status: string;
                address: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                geoLat: number | null;
                geoLng: number | null;
                endDate: Date | null;
                clientId: string | null;
                startDate: Date | null;
                code: string | null;
                radius: number | null;
                workOrder: string | null;
                taxOverrideInfo: string | null;
            } | null;
            callout: {
                id: string;
                businessId: string;
                status: string;
                type: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                reviewedByUserId: string | null;
                reasonCode: string;
                reasonNote: string | null;
                noticeAt: Date;
                documentationUrl: string | null;
                reviewedAt: Date | null;
                openedAt: Date | null;
                openedByUserId: string | null;
                resolvedAt: Date | null;
                shiftId: string;
                absentEmployeeId: string;
                resolvedByUserId: string | null;
                submittedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                status: string;
                type: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                reviewedByUserId: string | null;
                reasonCode: string;
                reasonNote: string | null;
                noticeAt: Date;
                documentationUrl: string | null;
                reviewedAt: Date | null;
                openedAt: Date | null;
                openedByUserId: string | null;
                resolvedAt: Date | null;
                shiftId: string;
                absentEmployeeId: string;
                resolvedByUserId: string | null;
                submittedByUserId: string | null;
            } | null;
        } & {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        })[];
        summary: {
            totalHours: number;
            totalBreakMinutes: number;
            payableHours: number;
            estimatedEarnings: number;
        };
    }>;
    getMyPeerShifts(userId: string, start: Date, end: Date): Promise<Shift[]>;
    updateShift(id: string, data: Prisma.ShiftUpdateInput, user: any): Promise<Shift>;
    deleteShift(id: string, user: any): Promise<Shift>;
    publishShifts(businessId: string, start: Date, end: Date, user: any): Promise<void>;
    autoSchedule(businessId: string, start: Date, end: Date, user: any, opts?: {
        clientId?: string;
    }): Promise<{
        assigned: number;
        unfilled: number;
        total: number;
    }>;
    getBusinessId(userId: string): Promise<string>;
    private validateAvailability;
    private nextAvailable;
    handleShiftReminders(): Promise<void>;
    getMyAvailability(userId: string): Promise<{
        day: string;
        available: boolean;
        start: string;
        end: string;
    }[]>;
    updateMyAvailability(userId: string, availabilityData: any[]): Promise<{
        success: boolean;
    }>;
    private sendReminder;
}
