import { SchedulingService } from './scheduling.service';
import { Prisma } from '@unitedlinkgroup/database';
export declare class SchedulingController {
    private readonly schedulingService;
    constructor(schedulingService: SchedulingService);
    createShift(data: Prisma.ShiftCreateInput, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }>;
    getShifts(queryBusinessId: string, headerBusinessId: string, start: string, end: string, employeeId: string, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }[]>;
    getMyShifts(start: string, end: string, req: any): Promise<{
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            hourlyRate: number;
        };
        shifts: ({
            employee: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
            location: {
                id: string;
                businessId: string;
                status: string;
                address: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                geoLat: number | null;
                geoLng: number | null;
                endDate: Date | null;
                clientId: string | null;
                startDate: Date | null;
                code: string | null;
                radius: number | null;
                workOrder: string | null;
                taxOverrideInfo: string | null;
            } | null;
            callout: {
                id: string;
                businessId: string;
                status: string;
                type: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                reviewedByUserId: string | null;
                reasonCode: string;
                reasonNote: string | null;
                noticeAt: Date;
                documentationUrl: string | null;
                reviewedAt: Date | null;
                openedAt: Date | null;
                openedByUserId: string | null;
                resolvedAt: Date | null;
                shiftId: string;
                absentEmployeeId: string;
                resolvedByUserId: string | null;
                submittedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                status: string;
                type: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                reviewedByUserId: string | null;
                reasonCode: string;
                reasonNote: string | null;
                noticeAt: Date;
                documentationUrl: string | null;
                reviewedAt: Date | null;
                openedAt: Date | null;
                openedByUserId: string | null;
                resolvedAt: Date | null;
                shiftId: string;
                absentEmployeeId: string;
                resolvedByUserId: string | null;
                submittedByUserId: string | null;
            } | null;
        } & {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        })[];
        summary: {
            totalHours: number;
            totalBreakMinutes: number;
            payableHours: number;
            estimatedEarnings: number;
        };
    }>;
    getMyCallouts(req: any): Promise<any>;
    getMyPeerShifts(start: string, end: string, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }[]>;
    applyForShift(id: string, req: any): Promise<any>;
    approveShiftApplication(id: string, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }>;
    declineShiftApplication(id: string, req: any): Promise<{
        success: boolean;
    }>;
    recordCallout(id: string, body: any, req: any, ip: string, userAgent: string): Promise<{
        shiftId: string;
        calloutId: any;
        status: string;
    }>;
    listPendingCallouts(req: any, businessId?: string): Promise<any>;
    approveCallout(id: string, req: any): Promise<{
        callout: any;
        notified: number;
    }>;
    rejectCallout(id: string, body: any, req: any): Promise<any>;
    reassignShift(id: string, body: any, req: any, ip: string, userAgent: string): Promise<{
        shift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        coverageId: any;
    }>;
    broadcastShift(id: string, body: any, req: any, ip: string, userAgent: string): Promise<{
        shiftId: string;
        notified: number;
    }>;
    shiftHistory(id: string, req: any): Promise<{
        shift: {
            [x: string]: ({
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            })[] | ({
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            } | {
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            })[] | ({
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            } | {
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            })[] | {
                id: string;
                businessId: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                rejectionReason: string | null;
                message: string | null;
                offeredEmployeeId: string;
                requestedEmployeeId: string;
                requesterEmployeeId: string;
                offeredShiftId: string;
                requestedShiftId: string;
                reviewedByUserId: string | null;
            }[] | {
                id: string;
                businessId: string;
                method: string;
                shiftId: string;
                absentEmployeeId: string | null;
                reassignedAt: Date;
                acceptedAt: Date | null;
                responseMinutes: number | null;
                calloutId: string | null;
                replacementEmployeeId: string;
                reassignedByUserId: string | null;
            }[] | {
                id: string;
                status: string;
                createdAt: Date;
                employeeId: string;
                shiftId: string;
            }[];
            [x: number]: never;
            [x: symbol]: never;
        } & {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        logs: {
            id: string;
            action: string;
            resource: string;
            resourceId: string | null;
            at: Date;
            by: string;
            details: any;
        }[];
    }>;
    updateShift(id: string, data: Prisma.ShiftUpdateInput, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }>;
    deleteShift(id: string, req: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: Date;
        startTime: Date;
        employeeId: string | null;
        locationId: string | null;
        notes: string | null;
        groupId: string | null;
        breakMinutes: number;
        reminderSent1h: boolean;
        reminderSent30m: boolean;
        reminderSent10m: boolean;
        reminderEnd5mSent: boolean;
        reminderEndLate10mSent: boolean;
        autoClockout1hDone: boolean;
    }>;
    publishShifts(queryBusinessId: string, headerBusinessId: string, start: string, end: string, req: any): Promise<void>;
    autoSchedule(queryBusinessId: string, headerBusinessId: string, start: string, end: string, clientId: string, req: any): Promise<{
        assigned: number;
        unfilled: number;
        total: number;
    }>;
    getMyAvailability(req: any): Promise<{
        day: string;
        available: boolean;
        start: string;
        end: string;
    }[]>;
    updateMyAvailability(body: any, req: any): Promise<{
        success: boolean;
    }>;
}
