import { PrismaService } from '../prisma.service';
import { Payroll } from '@unitedlinkgroup/database';
import { LeaveService } from '../leave/leave.service';
export declare class PayrollService {
    private prisma;
    private leave;
    constructor(prisma: PrismaService, leave: LeaveService);
    getBusinessId(userId: string): Promise<string>;
    getPayStubsForUser(userId: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        payroll: {
            business: {
                id: string;
                status: string;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                logoUrl: string | null;
                ein: string | null;
                mobile: string | null;
                currencyCode: string | null;
                governmentInfo: string | null;
                businessType: string | null;
                industry: string | null;
                employeeCount: string | null;
                modules: string | null;
                settings: string | null;
                ownerId: string;
            };
        } & {
            id: string;
            businessId: string;
            status: string;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            periodStart: Date;
            periodEnd: Date;
            payDate: Date;
            totalGross: number;
            totalNet: number;
            totalEmployeeTaxes: number;
            totalEmployerTaxes: number;
            totalDeductions: number;
        };
    } & {
        id: string;
        workerType: string;
        payrollId: string;
        createdAt: Date;
        employeeId: string;
        regularHours: number;
        overtimeHours: number;
        regularPay: number;
        overtimePay: number;
        bonus: number;
        commission: number;
        reimbursement: number;
        grossPay: number;
        netPay: number;
        ytdGross: number;
        ytdNet: number;
        ytdTaxes: number;
        taxes: number;
        employerTaxes: number;
        deductions: number;
        taxDetails: string | null;
        employerTaxDetails: string | null;
        deductionDetails: string | null;
    })[]>;
    getBusinessPayStubs(businessId: string, user?: any): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        payroll: {
            id: string;
            businessId: string;
            status: string;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            periodStart: Date;
            periodEnd: Date;
            payDate: Date;
            totalGross: number;
            totalNet: number;
            totalEmployeeTaxes: number;
            totalEmployerTaxes: number;
            totalDeductions: number;
        };
    } & {
        id: string;
        workerType: string;
        payrollId: string;
        createdAt: Date;
        employeeId: string;
        regularHours: number;
        overtimeHours: number;
        regularPay: number;
        overtimePay: number;
        bonus: number;
        commission: number;
        reimbursement: number;
        grossPay: number;
        netPay: number;
        ytdGross: number;
        ytdNet: number;
        ytdTaxes: number;
        taxes: number;
        employerTaxes: number;
        deductions: number;
        taxDetails: string | null;
        employerTaxDetails: string | null;
        deductionDetails: string | null;
    })[]>;
    downloadPayStubPdf(payStubId: string, user: any): Promise<{
        filename: string;
        data: Buffer;
    }>;
    private assertPayStubAccess;
    getPayrollsForUser(userId: string, user?: any): Promise<Payroll[]>;
    validateBusinessAccess(targetBusinessId: string, user: any): Promise<void>;
    createPayroll(businessId: string, periodStart: Date, periodEnd: Date, payDate: Date, type?: string, user?: any): Promise<Payroll>;
    getAnnualTaxReport(businessId: string, year: number, user?: any): Promise<{
        year: number;
        w2Employees: any[];
        contractors: any[];
        summary: {
            totalW2Gross: any;
            total1099Gross: any;
            totalTaxesWithheld: any;
            totalEmployerTaxes: any;
        };
    }>;
    getYearEndForms(businessId: string, year: number, user?: any): Promise<{
        year: number;
        w2s: {
            employeeId: any;
            ssn: any;
            name: string;
            address: string;
            wages: any;
            fedIncomeTax: any;
            socialSecurityWages: number;
            socialSecurityTax: any;
            medicareWages: any;
            medicareTax: any;
            stateWages: any;
            stateIncomeTax: any;
            employerName: string;
            employerEin: string | null;
            employerAddress: string;
        }[];
        nec1099s: {
            contractorId: any;
            tin: any;
            name: string;
            address: string;
            nonemployeeCompensation: any;
            fedTaxWithheld: number;
            stateTaxWithheld: number;
            payerName: string;
            payerTin: string | null;
            payerAddress: string;
        }[];
    }>;
    runPayrollCalculation(payrollId: string, user?: any): Promise<any>;
    updatePayStub(stubId: string, updates: {
        regularHours?: number;
        overtimeHours?: number;
        bonus?: number;
        commission?: number;
        reimbursement?: number;
        deductions?: number;
        federalTax?: number;
        socialSecurity?: number;
        medicare?: number;
        stateTax?: number;
    }, user?: any): Promise<{
        id: string;
        workerType: string;
        payrollId: string;
        createdAt: Date;
        employeeId: string;
        regularHours: number;
        overtimeHours: number;
        regularPay: number;
        overtimePay: number;
        bonus: number;
        commission: number;
        reimbursement: number;
        grossPay: number;
        netPay: number;
        ytdGross: number;
        ytdNet: number;
        ytdTaxes: number;
        taxes: number;
        employerTaxes: number;
        deductions: number;
        taxDetails: string | null;
        employerTaxDetails: string | null;
        deductionDetails: string | null;
    }>;
    private recalculatePayrollTotals;
    getPayrolls(businessId: string, user?: any): Promise<Payroll[]>;
    deletePayroll(id: string, user?: any): Promise<[import("@unitedlinkgroup/database").Prisma.BatchPayload, import("@unitedlinkgroup/database").Prisma.BatchPayload, {
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        periodStart: Date;
        periodEnd: Date;
        payDate: Date;
        totalGross: number;
        totalNet: number;
        totalEmployeeTaxes: number;
        totalEmployerTaxes: number;
        totalDeductions: number;
    }]>;
    getPayrollById(id: string, user?: any): Promise<any>;
    private calculateGrossPay;
    private getYTDGross;
    private getYTDTaxes;
    private calculateTaxes;
    finalizePayroll(payrollId: string, user?: any): Promise<Payroll>;
    private calculateDeductions;
}
