import { LoansService } from './loans.service';
export declare class LoansController {
    private readonly loansService;
    constructor(loansService: LoansService);
    create(req: any, createLoanDto: {
        amount: number;
        termMonths?: number;
        reason?: string;
        targetUserId?: string;
        targetEmployeeId?: string;
    }, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    }>;
    findAll(req: any, businessId?: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    })[]>;
    findMyLoans(req: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    }[]>;
    findOne(id: string, req: any, businessId?: string): Promise<{
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        repayments: {
            id: string;
            payrollId: string | null;
            amount: number;
            date: Date;
            loanId: string;
        }[];
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    }>;
    approve(id: string, req: any, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    }>;
    reject(id: string, body: {
        reason: string;
    }, req: any, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        amount: number;
        balance: number;
        termMonths: number;
        perPayPeriodDeduction: number;
        reason: string | null;
        approvedBy: string | null;
        rejectionReason: string | null;
    }>;
}
