import { PrismaService } from '../prisma.service';
import { CreateBusinessDto } from './dto/create-business.dto';
import { UpdateBusinessDto } from './dto/update-business.dto';
export declare class BusinessesService {
    private prisma;
    constructor(prisma: PrismaService);
    setStatus(id: string, status: 'ACTIVE' | 'INACTIVE' | 'DELETED'): Promise<{
        id: string;
        status: string;
        updatedAt: Date;
        name: string;
    }>;
    create(createBusinessDto: CreateBusinessDto, ownerId: string): Promise<{
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    }>;
    findAll(): Promise<({
        owner: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
        };
    } & {
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    })[]>;
    findOne(id: string): Promise<({
        owner: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
        };
    } & {
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    }) | null>;
    findMine(userId: string): Promise<{
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    } | null>;
    update(id: string, updateBusinessDto: UpdateBusinessDto): Promise<{
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    }>;
    updateForUser(user: any, pathId: string | undefined, updateBusinessDto: UpdateBusinessDto, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        logoUrl: string | null;
        ein: string | null;
        mobile: string | null;
        currencyCode: string | null;
        governmentInfo: string | null;
        businessType: string | null;
        industry: string | null;
        employeeCount: string | null;
        modules: string | null;
        settings: string | null;
        ownerId: string;
    }>;
}
