import { LeaveService } from './leave.service';
import { CreateLeaveTypeDto } from './dto/create-leave-type.dto';
import { CreateLeaveRequestDto } from './dto/create-leave-request.dto';
import { UpdateLeaveTypeDto } from './dto/update-leave-type.dto';
import { ResumeLeaveRequestDto } from './dto/resume-leave-request.dto';
import { CancelLeaveRequestDto } from './dto/cancel-leave-request.dto';
export declare class LeaveController {
    private readonly leaveService;
    constructor(leaveService: LeaveService);
    createType(body: CreateLeaveTypeDto & {
        businessId: string;
    }, req: any): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }>;
    calculateHours(employeeId: string, startDate: string, endDate: string, isAllDay?: string, startTime?: string, endTime?: string): Promise<{
        totalHours: any;
    }>;
    getTypes(businessId: string): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }[]>;
    updateType(id: string, body: UpdateLeaveTypeDto, req: any): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }>;
    assignBalance(body: {
        employeeId: string;
        leaveTypeId: string;
        hours: number;
    }, req: any): Promise<{
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    }>;
    getBalance(employeeId: string, user: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    })[]>;
    requestLeave(body: CreateLeaveRequestDto, user: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    getMyRequests(req: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    getEmployeeRequests(employeeId: string, req: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    getMyBalances(req: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    })[]>;
    getRequests(queryBusinessId: string, headerBusinessId: string, status?: string, req?: any): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    updateStatus(id: string, body: {
        status: 'APPROVED' | 'REJECTED';
        rejectionReason?: string;
    }, user: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    updateDetails(id: string, body: Partial<CreateLeaveRequestDto>, user: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    resumeLeave(id: string, body: ResumeLeaveRequestDto, user: any): Promise<any>;
    cancelLeave(id: string, body: CancelLeaveRequestDto, user: any): Promise<any>;
    accrue(body: {
        employeeId: string;
        leaveTypeId: string;
        method: 'PER_HOUR' | 'PER_PAY_PERIOD';
        periodStart?: string;
        periodEnd?: string;
    }, user: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    }) | null>;
    accruePayroll(body: {
        businessId: string;
        periodStart: string;
        periodEnd: string;
    }, user: any): Promise<{
        periodStart: Date;
        periodEnd: Date;
        count: number;
        results: {
            employeeId: string;
            leaveTypeId: string;
            method: string;
            accrued: number;
        }[];
    }>;
}
