import { PrismaService } from '../prisma.service';
import { CreateLeaveTypeDto } from './dto/create-leave-type.dto';
import { CreateLeaveRequestDto } from './dto/create-leave-request.dto';
import { UpdateLeaveTypeDto } from './dto/update-leave-type.dto';
export declare class LeaveService {
    private prisma;
    constructor(prisma: PrismaService);
    createLeaveType(businessId: string, dto: CreateLeaveTypeDto, user?: any): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }>;
    getLeaveTypes(businessId: string): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }[]>;
    updateLeaveType(id: string, dto: UpdateLeaveTypeDto, user?: any): Promise<{
        id: string;
        businessId: string;
        name: string;
        isPaid: boolean;
        allowNegative: boolean;
        requiresApproval: boolean;
        color: string | null;
        accrualFrequency: string | null;
        accrualRate: number | null;
        maxBalance: number | null;
        carryOverLimit: number | null;
    }>;
    private checkTenancy;
    private bootstrapDefaultLeaveTypes;
    assignLeaveBalance(employeeId: string, leaveTypeId: string, hours: number, user?: any): Promise<{
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    }>;
    getLeaveBalances(employeeId: string, user?: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    })[]>;
    requestLeave(dto: CreateLeaveRequestDto, user?: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    private getDailyScheduledHours;
    private calculateLeaveHoursInternal;
    getLeaveRequests(businessId: string, status?: string, user?: any): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    getBusinessId(userId: string): Promise<string>;
    getRequestsForUser(userId: string): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    getBalancesForUser(userId: string): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    })[]>;
    getMyLeaveRequests(employeeId: string, user?: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    })[]>;
    accrueLeave(employeeId: string, leaveTypeId: string, method: 'PER_HOUR' | 'PER_PAY_PERIOD', periodStart?: Date, periodEnd?: Date, user?: any): Promise<({
        leaveType: {
            id: string;
            businessId: string;
            name: string;
            isPaid: boolean;
            allowNegative: boolean;
            requiresApproval: boolean;
            color: string | null;
            accrualFrequency: string | null;
            accrualRate: number | null;
            maxBalance: number | null;
            carryOverLimit: number | null;
        };
    } & {
        id: string;
        employeeId: string;
        leaveTypeId: string;
        balanceHours: number;
        takenHours: number;
    }) | null>;
    accrueForPayrollPeriod(businessId: string, periodStart: Date, periodEnd: Date, user?: any): Promise<{
        periodStart: Date;
        periodEnd: Date;
        count: number;
        results: {
            employeeId: string;
            leaveTypeId: string;
            method: string;
            accrued: number;
        }[];
    }>;
    updateLeaveRequestStatus(id: string, managerId: string, status: 'APPROVED' | 'REJECTED', rejectionReason?: string, user?: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    updateLeaveRequestDetails(id: string, dto: Partial<CreateLeaveRequestDto>, user?: any): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        employeeId: string;
        leaveTypeId: string;
        reason: string | null;
        rejectionReason: string | null;
        endDate: Date;
        startDate: Date;
        isAllDay: boolean;
        totalHours: number;
        actualHours: number | null;
        resumedAt: Date | null;
        resumedReason: string | null;
        refundedHours: number | null;
        cancelledAt: Date | null;
        cancelledReason: string | null;
        managerId: string | null;
    }>;
    resumeLeaveEarly(id: string, dto: {
        resumedAt: string;
        resumedReason: string;
        resumedTime?: string;
    }, user?: any): Promise<any>;
    cancelApprovedLeave(id: string, dto: {
        reason: string;
        cancelledByLabel?: string;
    }, user?: any): Promise<any>;
    private calculateLeaveHoursUntilResume;
}
