import { EmployeesService } from './employees.service';
export declare class EmployeesController {
    private readonly employeesService;
    constructor(employeesService: EmployeesService);
    getMe(req: any, businessId?: string): Promise<{
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateMyProfileImage(req: any, body: {
        url: string;
    }, businessId?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateMyPassword(req: any, body: {
        currentPassword: string;
        newPassword: string;
    }, businessId?: string): Promise<{
        ok: boolean;
    }>;
    updateMyBio(req: any, body: any, businessId?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    listMyAvailability(req: any, businessId?: string): Promise<any>;
    createMyAvailability(req: any, body: any, businessId?: string): Promise<any>;
    updateMyAvailability(req: any, availabilityId: string, body: any, businessId?: string): Promise<any>;
    deleteMyAvailability(req: any, availabilityId: string, businessId?: string): Promise<any>;
    findAll(req: any, status?: string, businessId?: string): Promise<{
        ssn: string | null;
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    listChatDirectory(req: any, businessId?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        preferredName: string | null;
        displayName: string;
        email: string;
        badgeNumber: string | null;
        status: string;
        profileImageUrl: string | null;
        role: string;
        customRole: {
            name: string;
        } | null;
    }[]>;
    getExpiringQualifications(req: any, businessId?: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    })[]>;
    getAllQualifications(req: any, businessId?: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
        };
    } & {
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    })[]>;
    getMyQualifications(req: any, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }[]>;
    addMyQualification(req: any, body: any, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    updateMyQualification(req: any, qualificationId: string, body: any, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    deleteMyQualification(req: any, qualificationId: string, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    getAllAvailabilities(req: any, businessId?: string): Promise<any>;
    findOne(req: any, id: string, businessId?: string): Promise<{
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    create(req: any, body: any, businessId?: string): Promise<{
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(req: any, id: string, body: any, businessId?: string): Promise<{
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updatePassword(req: any, id: string, body: any, businessId?: string): Promise<{
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    listAvailability(req: any, id: string, businessId?: string): Promise<any>;
    createAvailability(req: any, id: string, body: any, businessId?: string): Promise<any>;
    updateAvailability(req: any, id: string, availabilityId: string, body: any, businessId?: string): Promise<any>;
    deleteAvailability(req: any, id: string, availabilityId: string, businessId?: string): Promise<any>;
    getQualifications(req: any, id: string, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }[]>;
    addQualification(req: any, id: string, body: any, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    updateQualification(req: any, qualificationId: string, body: any, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    deleteQualification(req: any, qualificationId: string, businessId?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
}
