import { PrismaService } from '../prisma.service';
import { EncryptionService } from '../common/security/encryption.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PushService } from '../push/push.service';
export declare class EmployeesService {
    private prisma;
    private encryptionService;
    private notificationsService;
    private push;
    private readonly logger;
    constructor(prisma: PrismaService, encryptionService: EncryptionService, notificationsService: NotificationsService, push: PushService);
    private getBusinessId;
    findAll(user: any, status?: string, businessIdHeader?: string): Promise<{
        ssn: string | null;
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    listChatDirectory(user: any, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        preferredName: string | null;
        displayName: string;
        email: string;
        badgeNumber: string | null;
        status: string;
        profileImageUrl: string | null;
        role: string;
        customRole: {
            name: string;
        } | null;
    }[]>;
    findOne(user: any, id: string, businessIdHeader?: string): Promise<{
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getMe(user: any, businessIdHeader?: string): Promise<{
        customRole: {
            id: string;
            businessId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            description: string | null;
            permissions: string;
            isSystem: boolean;
        } | null;
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateMyProfileImage(user: any, profileImageUrl: string, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateMyPassword(user: any, input: {
        currentPassword: string;
        newPassword: string;
    }, businessIdHeader?: string): Promise<{
        ok: boolean;
    }>;
    updateMyBio(user: any, data: any, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getExpiringQualifications(user: any, businessIdHeader?: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    })[]>;
    getAllQualifications(user: any, businessIdHeader?: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
        };
    } & {
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    })[]>;
    getMyQualifications(user: any, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }[]>;
    addMyQualification(user: any, data: any, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    updateMyQualification(user: any, qualificationId: string, data: any, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    deleteMyQualification(user: any, qualificationId: string, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    listMyAvailability(user: any, businessIdHeader?: string): Promise<any>;
    createMyAvailability(user: any, body: any, businessIdHeader?: string): Promise<any>;
    updateMyAvailability(user: any, availabilityId: string, body: any, businessIdHeader?: string): Promise<any>;
    deleteMyAvailability(user: any, availabilityId: string, businessIdHeader?: string): Promise<any>;
    getAllAvailabilities(user: any, businessIdHeader?: string): Promise<any>;
    create(user: any, data: any, businessIdHeader?: string): Promise<{
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    addQualification(user: any, employeeId: string, data: any, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    updateQualification(user: any, qualificationId: string, data: any, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    checkExpiringQualifications(): Promise<void>;
    deleteQualification(user: any, qualificationId: string, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }>;
    getQualifications(user: any, employeeId: string, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        employeeId: string;
        issuingOrganization: string | null;
        credentialId: string | null;
        issueDate: Date | null;
        expiryDate: Date | null;
        fileUrl: string | null;
    }[]>;
    update(user: any, id: string, data: any, businessIdHeader?: string): Promise<{
        w2Profile: {
            id: string;
            paySchedule: string;
            payType: string;
            overtimeEligible: boolean;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            createdAt: Date;
            updatedAt: Date;
            employeeId: string;
            rate: number;
        } | null;
        contractorProfile: {
            id: string;
            type: string | null;
            w9Confirmed: boolean;
            employeeId: string;
            businessName: string | null;
            rate: number;
            paymentMethod: string | null;
        } | null;
    } & {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    listAvailability(user: any, employeeId: string, businessIdHeader?: string): Promise<any>;
    createAvailability(user: any, employeeId: string, body: any, businessIdHeader?: string): Promise<any>;
    updateAvailability(user: any, employeeId: string, availabilityId: string, body: any, businessIdHeader?: string): Promise<any>;
    deleteAvailability(user: any, employeeId: string, availabilityId: string, businessIdHeader?: string): Promise<any>;
}
