import { SwapsService } from './swaps.service';
import { CreateShiftSwapDto } from './dto/create-shift-swap.dto';
export declare class SwapsController {
    private readonly swapsService;
    constructor(swapsService: SwapsService);
    list(req: any, headerBusinessId: string | undefined, queryBusinessId?: string, status?: string): Promise<({
        requesterEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        offeredShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        requestedShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    })[]>;
    listMy(req: any, headerBusinessId: string | undefined): Promise<({
        requesterEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        offeredShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        requestedShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    })[]>;
    create(req: any, headerBusinessId: string | undefined, dto: CreateShiftSwapDto): Promise<{
        requesterEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        offeredShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        requestedShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    }>;
    cancel(req: any, headerBusinessId: string | undefined, id: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    }>;
    approve(req: any, headerBusinessId: string | undefined, id: string): Promise<{
        requesterEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        offeredShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
        requestedShift: {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        } | {
            id: string;
            businessId: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: Date;
            startTime: Date;
            employeeId: string | null;
            locationId: string | null;
            notes: string | null;
            groupId: string | null;
            breakMinutes: number;
            reminderSent1h: boolean;
            reminderSent30m: boolean;
            reminderSent10m: boolean;
            reminderEnd5mSent: boolean;
            reminderEndLate10mSent: boolean;
            autoClockout1hDone: boolean;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    }>;
    reject(req: any, headerBusinessId: string | undefined, id: string, body: {
        rejectionReason?: string;
    }): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        rejectionReason: string | null;
        message: string | null;
        offeredEmployeeId: string;
        requestedEmployeeId: string;
        requesterEmployeeId: string;
        offeredShiftId: string;
        requestedShiftId: string;
        reviewedByUserId: string | null;
    }>;
}
