import { PrismaService } from '../prisma.service';
import { CreateServicePinDto } from './dto/create-service-pin.dto';
import { UpdateServicePinDto } from './dto/update-service-pin.dto';
export declare class ServicePinsService {
    private prisma;
    constructor(prisma: PrismaService);
    private getBusinessId;
    private validateLocationAccess;
    create(user: any, createServicePinDto: CreateServicePinDto, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    findAllByLocation(user: any, locationId: string, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }[]>;
    findOne(user: any, id: string, businessIdHeader?: string): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    update(user: any, id: string, updateServicePinDto: UpdateServicePinDto, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    remove(user: any, id: string, businessIdHeader?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
}
