import { ServicePinsService } from './service-pins.service';
import { CreateServicePinDto } from './dto/create-service-pin.dto';
import { UpdateServicePinDto } from './dto/update-service-pin.dto';
export declare class ServicePinsController {
    private readonly servicePinsService;
    constructor(servicePinsService: ServicePinsService);
    create(req: any, createServicePinDto: CreateServicePinDto, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    findAllByLocation(req: any, locationId: string, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }[]>;
    findOne(req: any, id: string, businessId?: string): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        };
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    update(req: any, id: string, updateServicePinDto: UpdateServicePinDto, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
    remove(req: any, id: string, businessId?: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        endTime: string | null;
        startTime: string | null;
        locationId: string;
        geoLat: number | null;
        geoLng: number | null;
        days: string | null;
        count: number;
        positionType: string;
        shiftType: string;
        payRate: number | null;
        specialInstructions: string | null;
    }>;
}
