import { PrismaService } from '../prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PushService } from '../push/push.service';
import { CreateEmployeeFormTemplateDto } from './dto/create-employee-form-template.dto';
import { UpdateEmployeeFormTemplateDto } from './dto/update-employee-form-template.dto';
import { AssignEmployeeFormTemplateDto } from './dto/assign-employee-form-template.dto';
import { SubmitEmployeeFormAssignmentDto } from './dto/submit-employee-form-assignment.dto';
export declare class EmployeeFormsService {
    private prisma;
    private notifications;
    private push;
    constructor(prisma: PrismaService, notifications: NotificationsService, push: PushService);
    private resolveActorUserId;
    private getBusinessIdFromUser;
    private validateBusinessAccess;
    private resolveBusinessId;
    listTemplates(user: any, businessIdHeader?: string, query?: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        title: string;
        description: string | null;
        fileUrl: string | null;
        createdByUserId: string | null;
        version: string | null;
        acknowledgementRequired: boolean;
        fields: string | null;
        requiresSignature: boolean;
    }[]>;
    createTemplate(user: any, dto: CreateEmployeeFormTemplateDto, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        title: string;
        description: string | null;
        fileUrl: string | null;
        createdByUserId: string | null;
        version: string | null;
        acknowledgementRequired: boolean;
        fields: string | null;
        requiresSignature: boolean;
    }>;
    updateTemplate(user: any, id: string, dto: UpdateEmployeeFormTemplateDto): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        title: string;
        description: string | null;
        fileUrl: string | null;
        createdByUserId: string | null;
        version: string | null;
        acknowledgementRequired: boolean;
        fields: string | null;
        requiresSignature: boolean;
    }>;
    archiveTemplate(user: any, id: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        title: string;
        description: string | null;
        fileUrl: string | null;
        createdByUserId: string | null;
        version: string | null;
        acknowledgementRequired: boolean;
        fields: string | null;
        requiresSignature: boolean;
    }>;
    assignTemplate(user: any, templateId: string, dto: AssignEmployeeFormTemplateDto, businessIdHeader?: string): Promise<{
        assigned: number;
        failed: number;
    }>;
    listAssignmentsAdmin(user: any, businessIdHeader?: string, query?: any): Promise<({
        [x: string]: never;
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        values: string | null;
        dueAt: Date | null;
        templateId: string;
        assignedAt: Date;
        submittedAt: Date | null;
        signatureName: string | null;
        signatureData: string | null;
        signedAt: Date | null;
    })[]>;
    listMyAssignments(user: any, query?: any): Promise<({
        [x: string]: never;
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        values: string | null;
        dueAt: Date | null;
        templateId: string;
        assignedAt: Date;
        submittedAt: Date | null;
        signatureName: string | null;
        signatureData: string | null;
        signedAt: Date | null;
    })[]>;
    getMyAssignment(user: any, id: string): Promise<{
        [x: string]: never;
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        values: string | null;
        dueAt: Date | null;
        templateId: string;
        assignedAt: Date;
        submittedAt: Date | null;
        signatureName: string | null;
        signatureData: string | null;
        signedAt: Date | null;
    }>;
    submitMyAssignment(user: any, id: string, dto: SubmitEmployeeFormAssignmentDto): Promise<any>;
    adminGetAssignment(user: any, id: string): Promise<{
        [x: string]: never;
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        values: string | null;
        dueAt: Date | null;
        templateId: string;
        assignedAt: Date;
        submittedAt: Date | null;
        signatureName: string | null;
        signatureData: string | null;
        signedAt: Date | null;
    }>;
}
