import { PrismaService } from '../prisma.service';
import { CreateClientDto } from './dto/create-client.dto';
import { UpdateClientDto } from './dto/update-client.dto';
export declare class ClientsService {
    private prisma;
    constructor(prisma: PrismaService);
    private validateBusinessAccess;
    create(user: any, createClientDto: CreateClientDto, businessId?: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
    findAll(user: any, businessId?: string): Promise<({
        _count: {
            locations: number;
        };
    } & {
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    })[]>;
    findOne(id: string, user: any): Promise<{
        locations: ({
            servicePins: {
                id: string;
                status: string;
                createdAt: Date;
                updatedAt: Date;
                endTime: string | null;
                startTime: string | null;
                locationId: string;
                geoLat: number | null;
                geoLng: number | null;
                days: string | null;
                count: number;
                positionType: string;
                shiftType: string;
                payRate: number | null;
                specialInstructions: string | null;
            }[];
        } & {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        })[];
    } & {
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
    update(id: string, updateClientDto: UpdateClientDto, user: any): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
    remove(id: string, user: any): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
}
