import { PrismaService } from '../prisma.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { SmtpMailerService } from '../common/email/smtp-mailer.service';
export declare class InvoicesService {
    private prisma;
    private mailer;
    constructor(prisma: PrismaService, mailer: SmtpMailerService);
    private validateBusinessAccess;
    private getBusinessId;
    createClient(data: {
        name: string;
        email?: string;
        phone?: string;
        address?: string;
    }, user: any, businessIdHeader?: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
    findAllClients(user: any, businessIdHeader?: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }[]>;
    createInvoice(data: CreateInvoiceDto, user: any, businessIdHeader?: string): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    updateInvoice(id: string, data: Partial<CreateInvoiceDto>, user: any): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    findAllInvoices(user: any, businessIdHeader?: string): Promise<({
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    })[]>;
    findAllByClient(clientId: string, user: any): Promise<({
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    })[]>;
    findOneInvoice(id: string, user: any): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    sendInvoice(id: string, user: any): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
}
