import { InvoicesService } from './invoices.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
export declare class InvoicesController {
    private readonly invoicesService;
    constructor(invoicesService: InvoicesService);
    createClient(req: any, createClientDto: {
        name: string;
        email?: string;
        phone?: string;
        address?: string;
    }, headerBusinessId?: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }>;
    findAllClients(req: any, headerBusinessId?: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        businessId: string;
        status: string;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        industry: string | null;
        street: string | null;
        contactPerson: string | null;
        alternateContact: string | null;
        billingAddressSameAsOffice: boolean;
        billingAddress: string | null;
        billingContactEmail: string | null;
        billingContactEmail2: string | null;
        billingContactEmail3: string | null;
        paymentTerms: string | null;
    }[]>;
    createInvoice(req: any, createInvoiceDto: CreateInvoiceDto, headerBusinessId?: string): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    updateInvoice(req: any, id: string, updateData: Partial<CreateInvoiceDto>): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    sendInvoice(req: any, id: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
    getInvoiceEmailConfig(): {
        configured: boolean;
        smtp: {
            host: string | null;
            port: string | null;
            secure: string | null;
            userSet: boolean;
            passSet: boolean;
        };
        mail: {
            from: string | null;
            replyTo: string | null;
            cc: string | null;
        };
    };
    findAllInvoices(req: any, headerBusinessId?: string): Promise<({
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    })[]>;
    findAllByClient(clientId: string, req: any): Promise<({
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    })[]>;
    findOneInvoice(id: string, req: any): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        };
        items: {
            id: string;
            amount: number;
            description: string;
            rate: number;
            quantity: number;
            invoiceId: string;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        issueDate: Date;
        clientId: string;
        notes: string | null;
        total: number;
        dueDate: Date;
        invoiceNumber: string;
        subtotal: number;
        taxRate: number;
        taxAmount: number;
    }>;
}
