import { PrismaService } from '../prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreateDepartmentDto } from './dto/create-department.dto';
import { UpdateDepartmentDto } from './dto/update-department.dto';
export declare class DepartmentsService {
    private prisma;
    private auditService;
    constructor(prisma: PrismaService, auditService: AuditService);
    private getBusinessId;
    create(createDepartmentDto: CreateDepartmentDto, user: any, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
    findAll(user: any, businessIdHeader?: string, status?: string): Promise<{
        employeeCount: number;
        activeEmployeeCount: number;
        inactiveEmployeeCount: number;
        _count: {
            employees: number;
        };
        employees: {
            id: string;
            status: string;
        }[];
        manager: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }[]>;
    findOne(id: string, user: any, businessIdHeader?: string): Promise<{
        employees: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        manager: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    } & {
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
    getDepartmentMembers(id: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        role: string;
        status: string;
        departmentId: string | null;
        w2Profile: {
            id: string;
        } | null;
        contractorProfile: {
            id: string;
        } | null;
    }[]>;
    addMember(id: string, employeeId: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    removeMember(id: string, employeeId: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    assignManager(id: string, employeeId: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
    removeManager(id: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
    update(id: string, updateDepartmentDto: UpdateDepartmentDto, user: any, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
    remove(id: string, user: any, businessIdHeader?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        managerId: string | null;
    }>;
}
