import { AssetsService } from './assets.service';
import { CreateAssetDto } from './dto/create-asset.dto';
import { AssignAssetDto } from './dto/assign-asset.dto';
export declare class AssetsController {
    private readonly assetsService;
    constructor(assetsService: AssetsService);
    create(req: any, createDto: CreateAssetDto, headerBusinessId?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    }>;
    assign(req: any, id: string, assignDto: AssignAssetDto): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    } | null>;
    returnAsset(req: any, id: string, data: {
        returnDate: string;
        condition: string;
        notes?: string;
    }): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    }>;
    getHistory(req: any, id: string): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        employeeId: string;
        notes: string | null;
        assignedDate: Date;
        assetId: string;
        returnedDate: Date | null;
        returnCondition: string | null;
    })[]>;
    findAll(req: any, headerBusinessId?: string): Promise<({
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        assignedTo: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    } & {
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    })[]>;
    findOne(id: string, req: any): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        assignedTo: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        children: ({
            assignedTo: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
        } & {
            id: string;
            businessId: string;
            status: string;
            type: string | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            locationId: string | null;
            color: string | null;
            vendor: string | null;
            description: string | null;
            category: string;
            notes: string | null;
            serialNumber: string | null;
            brand: string | null;
            model: string | null;
            size: string | null;
            condition: string | null;
            quantity: number;
            licenseNumber: string | null;
            complianceChecked: boolean;
            purchaseDate: Date | null;
            purchaseCost: number | null;
            warrantyExpiration: Date | null;
            assignedToId: string | null;
            assignedDate: Date | null;
            expectedReturnDate: Date | null;
            parentId: string | null;
        })[];
    } & {
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    }>;
    update(req: any, id: string, updateDto: Partial<CreateAssetDto>): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    }>;
    remove(req: any, id: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string | null;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        locationId: string | null;
        color: string | null;
        vendor: string | null;
        description: string | null;
        category: string;
        notes: string | null;
        serialNumber: string | null;
        brand: string | null;
        model: string | null;
        size: string | null;
        condition: string | null;
        quantity: number;
        licenseNumber: string | null;
        complianceChecked: boolean;
        purchaseDate: Date | null;
        purchaseCost: number | null;
        warrantyExpiration: Date | null;
        assignedToId: string | null;
        assignedDate: Date | null;
        expectedReturnDate: Date | null;
        parentId: string | null;
    }>;
}
