import { PrismaService } from '../prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreateRoleDto } from './dto/create-role.dto';
import { UpdateRoleDto } from './dto/update-role.dto';
export declare class RolesService {
    private prisma;
    private auditService;
    constructor(prisma: PrismaService, auditService: AuditService);
    create(createRoleDto: CreateRoleDto, businessId: string, userId: string): Promise<{
        id: string;
        businessId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        permissions: string;
        isSystem: boolean;
    }>;
    findAll(businessId: string): Promise<{
        permissions: any;
        memberCount: number;
        _count: {
            employees: number;
        };
        id: string;
        businessId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        isSystem: boolean;
    }[]>;
    getRoleMembers(id: string, businessId: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        role: string;
        departmentId: string | null;
    }[]>;
    addMember(id: string, employeeId: string, userId: string, businessId: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    removeMember(id: string, employeeId: string, userId: string, businessId: string): Promise<{
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phone: string | null;
        badgeNumber: string | null;
        profileImageUrl: string | null;
        businessId: string;
        userId: string | null;
        role: string;
        customRoleId: string | null;
        status: string;
        preferredName: string | null;
        pronouns: string | null;
        middleName: string | null;
        dateOfBirth: Date | null;
        isAuthorizedToWork: boolean;
        address: string | null;
        city: string | null;
        state: string | null;
        zip: string | null;
        country: string | null;
        officialEmail: string | null;
        emergencyContactName: string | null;
        emergencyContactPhone: string | null;
        type: string;
        workerType: string;
        paySchedule: string;
        payType: string;
        hourlyRate: number | null;
        salary: number | null;
        hireDate: Date | null;
        payrollId: string | null;
        workPeriod: string | null;
        hoursPerPeriod: number | null;
        daysPerPeriod: number | null;
        stressProfile: string | null;
        overtimeEligible: boolean;
        departmentId: string | null;
        defaultLocationId: string | null;
        supervisorId: string | null;
        ssn: string | null;
        filingStatus: string | null;
        taxState: string;
        federalAllowances: number;
        multipleJobs: boolean;
        dependentsAmount: number;
        otherIncome: number;
        deductionsAmount: number;
        additionalWithholding: number;
        stateFilingStatus: string | null;
        stateAllowances: number;
        stateAdditionalWithholding: number;
        contractorBusinessName: string | null;
        contractorType: string | null;
        w9Confirmed: boolean;
        directDepositInfo: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findOne(id: string, businessId: string): Promise<{
        permissions: any;
        id: string;
        businessId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        isSystem: boolean;
    } | null>;
    update(id: string, updateRoleDto: UpdateRoleDto, userId: string, businessId: string): Promise<{
        id: string;
        businessId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        permissions: string;
        isSystem: boolean;
    }>;
    remove(id: string, userId: string, businessId: string): Promise<{
        id: string;
        businessId: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        description: string | null;
        permissions: string;
        isSystem: boolean;
    }>;
}
