import { LocationsService } from './locations.service';
import { CreateLocationDto } from './dto/create-location.dto';
import { UpdateLocationDto } from './dto/update-location.dto';
export declare class LocationsController {
    private readonly locationsService;
    constructor(locationsService: LocationsService);
    create(req: any, body: CreateLocationDto, businessId?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        address: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        geoLat: number | null;
        geoLng: number | null;
        endDate: Date | null;
        clientId: string | null;
        startDate: Date | null;
        code: string | null;
        radius: number | null;
        workOrder: string | null;
        taxOverrideInfo: string | null;
    }>;
    findAll(req: any, businessId?: string, clientId?: string, status?: string): Promise<({
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        } | null;
        servicePins: {
            id: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: string | null;
            startTime: string | null;
            locationId: string;
            geoLat: number | null;
            geoLng: number | null;
            days: string | null;
            count: number;
            positionType: string;
            shiftType: string;
            payRate: number | null;
            specialInstructions: string | null;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        address: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        geoLat: number | null;
        geoLng: number | null;
        endDate: Date | null;
        clientId: string | null;
        startDate: Date | null;
        code: string | null;
        radius: number | null;
        workOrder: string | null;
        taxOverrideInfo: string | null;
    })[]>;
    findOne(req: any, id: string, businessId?: string): Promise<{
        client: {
            id: string;
            email: string | null;
            phone: string | null;
            businessId: string;
            status: string;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            industry: string | null;
            street: string | null;
            contactPerson: string | null;
            alternateContact: string | null;
            billingAddressSameAsOffice: boolean;
            billingAddress: string | null;
            billingContactEmail: string | null;
            billingContactEmail2: string | null;
            billingContactEmail3: string | null;
            paymentTerms: string | null;
        } | null;
        servicePins: {
            id: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            endTime: string | null;
            startTime: string | null;
            locationId: string;
            geoLat: number | null;
            geoLng: number | null;
            days: string | null;
            count: number;
            positionType: string;
            shiftType: string;
            payRate: number | null;
            specialInstructions: string | null;
        }[];
    } & {
        id: string;
        businessId: string;
        status: string;
        address: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        geoLat: number | null;
        geoLng: number | null;
        endDate: Date | null;
        clientId: string | null;
        startDate: Date | null;
        code: string | null;
        radius: number | null;
        workOrder: string | null;
        taxOverrideInfo: string | null;
    }>;
    update(req: any, id: string, body: UpdateLocationDto, businessId?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        address: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        geoLat: number | null;
        geoLng: number | null;
        endDate: Date | null;
        clientId: string | null;
        startDate: Date | null;
        code: string | null;
        radius: number | null;
        workOrder: string | null;
        taxOverrideInfo: string | null;
    }>;
    remove(req: any, id: string, businessId?: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        address: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        geoLat: number | null;
        geoLng: number | null;
        endDate: Date | null;
        clientId: string | null;
        startDate: Date | null;
        code: string | null;
        radius: number | null;
        workOrder: string | null;
        taxOverrideInfo: string | null;
    }>;
}
