import { IncidentReportsService } from './incident-reports.service';
import { CreateIncidentReportDto } from './dto/create-incident-report.dto';
import { Response } from 'express';
import { UploadsService } from '../uploads/uploads.service';
export declare class IncidentReportsController {
    private readonly incidentReportsService;
    private readonly uploadsService;
    constructor(incidentReportsService: IncidentReportsService, uploadsService: UploadsService);
    create(req: any, createDto: CreateIncidentReportDto, headerBusinessId?: string): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        reportingOfficer: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        submittedBy: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
        assignedSupervisor: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        assignedInvestigator: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        persons: {
            id: string;
            role: string;
            createdAt: Date;
            name: string;
            incidentId: string;
            contactInfo: string | null;
        }[];
        evidence: {
            id: string;
            createdAt: Date;
            kind: string;
            url: string;
            filename: string;
            originalName: string;
            mimeType: string | null;
            sizeBytes: number | null;
            incidentId: string;
            uploadedById: string;
        }[];
        timeline: {
            id: string;
            createdAt: Date;
            incidentId: string;
            eventType: string;
            payload: string | null;
            actorUserId: string | null;
        }[];
        reporter: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
    } & {
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        shift: string | null;
        title: string;
        geoLat: number | null;
        geoLng: number | null;
        reportNumber: string | null;
        description: string;
        severity: string;
        date: Date;
        incidentAt: Date | null;
        reportedAt: Date;
        buildingArea: string | null;
        responseAction: string | null;
        witnessPresent: boolean;
        lawEnforcementInvolved: boolean;
        evidenceCollected: string | null;
        images: string | null;
        deviceInfo: string | null;
        reportingOfficerEmployeeId: string | null;
        submittedById: string | null;
        assignedSupervisorId: string | null;
        assignedInvestigatorId: string | null;
        reporterId: string | null;
    }>;
    findAll(req: any, headerBusinessId?: string, page?: string, pageSize?: string, search?: string, locationId?: string, type?: string, severity?: string, status?: string, reportingOfficerEmployeeId?: string, from?: string, to?: string): Promise<{
        items: ({
            location: {
                id: string;
                businessId: string;
                status: string;
                address: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                geoLat: number | null;
                geoLng: number | null;
                endDate: Date | null;
                clientId: string | null;
                startDate: Date | null;
                code: string | null;
                radius: number | null;
                workOrder: string | null;
                taxOverrideInfo: string | null;
            } | null;
            reportingOfficer: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
            submittedBy: {
                id: string;
                firstName: string | null;
                lastName: string | null;
                email: string;
                role: string;
                createdAt: Date;
                updatedAt: Date;
                password: string;
            } | null;
            assignedSupervisor: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
            assignedInvestigator: {
                id: string;
                firstName: string;
                lastName: string;
                email: string;
                phone: string | null;
                badgeNumber: string | null;
                profileImageUrl: string | null;
                businessId: string;
                userId: string | null;
                role: string;
                customRoleId: string | null;
                status: string;
                preferredName: string | null;
                pronouns: string | null;
                middleName: string | null;
                dateOfBirth: Date | null;
                isAuthorizedToWork: boolean;
                address: string | null;
                city: string | null;
                state: string | null;
                zip: string | null;
                country: string | null;
                officialEmail: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                type: string;
                workerType: string;
                paySchedule: string;
                payType: string;
                hourlyRate: number | null;
                salary: number | null;
                hireDate: Date | null;
                payrollId: string | null;
                workPeriod: string | null;
                hoursPerPeriod: number | null;
                daysPerPeriod: number | null;
                stressProfile: string | null;
                overtimeEligible: boolean;
                departmentId: string | null;
                defaultLocationId: string | null;
                supervisorId: string | null;
                ssn: string | null;
                filingStatus: string | null;
                taxState: string;
                federalAllowances: number;
                multipleJobs: boolean;
                dependentsAmount: number;
                otherIncome: number;
                deductionsAmount: number;
                additionalWithholding: number;
                stateFilingStatus: string | null;
                stateAllowances: number;
                stateAdditionalWithholding: number;
                contractorBusinessName: string | null;
                contractorType: string | null;
                w9Confirmed: boolean;
                directDepositInfo: string | null;
                createdAt: Date;
                updatedAt: Date;
            } | null;
            evidence: {
                id: string;
                createdAt: Date;
                kind: string;
                url: string;
                filename: string;
                originalName: string;
                mimeType: string | null;
                sizeBytes: number | null;
                incidentId: string;
                uploadedById: string;
            }[];
        } & {
            id: string;
            businessId: string;
            status: string;
            type: string;
            createdAt: Date;
            updatedAt: Date;
            locationId: string | null;
            shift: string | null;
            title: string;
            geoLat: number | null;
            geoLng: number | null;
            reportNumber: string | null;
            description: string;
            severity: string;
            date: Date;
            incidentAt: Date | null;
            reportedAt: Date;
            buildingArea: string | null;
            responseAction: string | null;
            witnessPresent: boolean;
            lawEnforcementInvolved: boolean;
            evidenceCollected: string | null;
            images: string | null;
            deviceInfo: string | null;
            reportingOfficerEmployeeId: string | null;
            submittedById: string | null;
            assignedSupervisorId: string | null;
            assignedInvestigatorId: string | null;
            reporterId: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    getLocationSummary(req: any, headerBusinessId?: string, status?: string): Promise<any[]>;
    getAnalytics(req: any, headerBusinessId?: string, period?: string): Promise<{
        trend: {
            date: string;
            count: number;
        }[];
        byType: {
            type: string;
            count: number;
        }[];
        bySeverity: {
            severity: string;
            count: number;
        }[];
        byLocation: {
            locationId: string;
            locationName: string;
            count: number;
        }[];
        byOfficer: {
            employeeId: string;
            officerName: string;
            badgeNumber: any;
            count: number;
        }[];
    }>;
    export(req: any, headerBusinessId: string | undefined, res: Response, format?: string, search?: string, locationId?: string, type?: string, severity?: string, status?: string, reportingOfficerEmployeeId?: string, from?: string, to?: string): Promise<string | Buffer<ArrayBufferLike>>;
    findOne(id: string, req: any): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        reportingOfficer: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        submittedBy: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
        assignedSupervisor: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        assignedInvestigator: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        persons: {
            id: string;
            role: string;
            createdAt: Date;
            name: string;
            incidentId: string;
            contactInfo: string | null;
        }[];
        evidence: {
            id: string;
            createdAt: Date;
            kind: string;
            url: string;
            filename: string;
            originalName: string;
            mimeType: string | null;
            sizeBytes: number | null;
            incidentId: string;
            uploadedById: string;
        }[];
        timeline: {
            id: string;
            createdAt: Date;
            incidentId: string;
            eventType: string;
            payload: string | null;
            actorUserId: string | null;
        }[];
        reporter: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
    } & {
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        shift: string | null;
        title: string;
        geoLat: number | null;
        geoLng: number | null;
        reportNumber: string | null;
        description: string;
        severity: string;
        date: Date;
        incidentAt: Date | null;
        reportedAt: Date;
        buildingArea: string | null;
        responseAction: string | null;
        witnessPresent: boolean;
        lawEnforcementInvolved: boolean;
        evidenceCollected: string | null;
        images: string | null;
        deviceInfo: string | null;
        reportingOfficerEmployeeId: string | null;
        submittedById: string | null;
        assignedSupervisorId: string | null;
        assignedInvestigatorId: string | null;
        reporterId: string | null;
    }>;
    update(req: any, id: string, updateDto: Partial<CreateIncidentReportDto>): Promise<{
        location: {
            id: string;
            businessId: string;
            status: string;
            address: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            geoLat: number | null;
            geoLng: number | null;
            endDate: Date | null;
            clientId: string | null;
            startDate: Date | null;
            code: string | null;
            radius: number | null;
            workOrder: string | null;
            taxOverrideInfo: string | null;
        } | null;
        reportingOfficer: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        submittedBy: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
        assignedSupervisor: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        assignedInvestigator: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phone: string | null;
            badgeNumber: string | null;
            profileImageUrl: string | null;
            businessId: string;
            userId: string | null;
            role: string;
            customRoleId: string | null;
            status: string;
            preferredName: string | null;
            pronouns: string | null;
            middleName: string | null;
            dateOfBirth: Date | null;
            isAuthorizedToWork: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            zip: string | null;
            country: string | null;
            officialEmail: string | null;
            emergencyContactName: string | null;
            emergencyContactPhone: string | null;
            type: string;
            workerType: string;
            paySchedule: string;
            payType: string;
            hourlyRate: number | null;
            salary: number | null;
            hireDate: Date | null;
            payrollId: string | null;
            workPeriod: string | null;
            hoursPerPeriod: number | null;
            daysPerPeriod: number | null;
            stressProfile: string | null;
            overtimeEligible: boolean;
            departmentId: string | null;
            defaultLocationId: string | null;
            supervisorId: string | null;
            ssn: string | null;
            filingStatus: string | null;
            taxState: string;
            federalAllowances: number;
            multipleJobs: boolean;
            dependentsAmount: number;
            otherIncome: number;
            deductionsAmount: number;
            additionalWithholding: number;
            stateFilingStatus: string | null;
            stateAllowances: number;
            stateAdditionalWithholding: number;
            contractorBusinessName: string | null;
            contractorType: string | null;
            w9Confirmed: boolean;
            directDepositInfo: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        persons: {
            id: string;
            role: string;
            createdAt: Date;
            name: string;
            incidentId: string;
            contactInfo: string | null;
        }[];
        evidence: {
            id: string;
            createdAt: Date;
            kind: string;
            url: string;
            filename: string;
            originalName: string;
            mimeType: string | null;
            sizeBytes: number | null;
            incidentId: string;
            uploadedById: string;
        }[];
        timeline: {
            id: string;
            createdAt: Date;
            incidentId: string;
            eventType: string;
            payload: string | null;
            actorUserId: string | null;
        }[];
        reporter: {
            id: string;
            firstName: string | null;
            lastName: string | null;
            email: string;
            role: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
        } | null;
    } & {
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        shift: string | null;
        title: string;
        geoLat: number | null;
        geoLng: number | null;
        reportNumber: string | null;
        description: string;
        severity: string;
        date: Date;
        incidentAt: Date | null;
        reportedAt: Date;
        buildingArea: string | null;
        responseAction: string | null;
        witnessPresent: boolean;
        lawEnforcementInvolved: boolean;
        evidenceCollected: string | null;
        images: string | null;
        deviceInfo: string | null;
        reportingOfficerEmployeeId: string | null;
        submittedById: string | null;
        assignedSupervisorId: string | null;
        assignedInvestigatorId: string | null;
        reporterId: string | null;
    }>;
    addNote(req: any, id: string, body: {
        note?: string;
    }): Promise<{
        ok: boolean;
    }>;
    assignInvestigator(req: any, id: string, body: {
        investigatorEmployeeId?: string;
    }): Promise<{
        ok: boolean;
    }>;
    uploadEvidence(req: any, id: string, file: any): Promise<{
        id: string;
        createdAt: Date;
        kind: string;
        url: string;
        filename: string;
        originalName: string;
        mimeType: string | null;
        sizeBytes: number | null;
        incidentId: string;
        uploadedById: string;
    }>;
    remove(req: any, id: string): Promise<{
        id: string;
        businessId: string;
        status: string;
        type: string;
        createdAt: Date;
        updatedAt: Date;
        locationId: string | null;
        shift: string | null;
        title: string;
        geoLat: number | null;
        geoLng: number | null;
        reportNumber: string | null;
        description: string;
        severity: string;
        date: Date;
        incidentAt: Date | null;
        reportedAt: Date;
        buildingArea: string | null;
        responseAction: string | null;
        witnessPresent: boolean;
        lawEnforcementInvolved: boolean;
        evidenceCollected: string | null;
        images: string | null;
        deviceInfo: string | null;
        reportingOfficerEmployeeId: string | null;
        submittedById: string | null;
        assignedSupervisorId: string | null;
        assignedInvestigatorId: string | null;
        reporterId: string | null;
    }>;
}
